name: luffy
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Desktop-specific dependencies
  media_kit: ^1.1.0
  # media_kit_video: ^1.1.0
  media_kit_libs_video: ^1.0.1
  media_kit_libs_windows_video: ^1.0.4
  media_kit_native_event_loop: ^1.0.6
  webview_windows: ^0.2.2
  window_manager: ^0.3.5
  # ---
  flutter_inappwebview: ^6.0.0-beta.22
  url_launcher: ^6.1.10
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.2
  intl: ^0.18.1
  custom_refresh_indicator: ^2.0.1
  video_player: ^2.7.2
  screen_brightness: ^0.2.2
  flutter_volume_controller: ^1.2.5
  html: ^0.15.3
  tuple: ^2.0.1
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  scrollable_positioned_list: ^0.3.8
  collection: ^1.17.0
  string_similarity: ^2.0.0
  dart_des: ^1.0.2
  cookie_jar: ^4.0.2
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  dio_cookie_manager: ^3.1.0+1
  dio: ^5.1.2
  flutter_displaymode: ^0.6.0
  flutter_html: ^3.0.0-beta.2
  hex: ^0.2.0
  color_log: ^0.0.6
  wakelock_plus: ^1.1.4
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.15.1
  innosetup: ^0.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/mal.svg
    - assets/images/logo.png

msix_config:
  display_name: Luffy
  publisher_display_name: Xminent
  identity_name: com.xminent.luffy
  msix_version: 1.0.0.0
  logo_path: ./assets/images/logo.png
  capabilities: internetClient
